language: node_js
node_js:
  - "10"

env:
  - TRAVIS_CI=1

cache: npm

install:
  - npm i

script:
  - npm run lint
  - npm run test

after_script:
    - npm run coveralls

branches:
  only:
    - master
    - dev
  